function P(n){const a=[];for(let i=0;i<n;i++)a.push(new Array(n).fill(false));return a}
function B(){this.buffer=[];this.length=0}B.prototype={put:function(v,l){for(let i=l-1;i>=0;i--)this.putBit(((v>>>i)&1)===1)},putBit:function(b){const i=this.length>>3;this.buffer[i]=this.buffer[i]||0;if(b)this.buffer[i]|=0x80>>(this.length%8);this.length++}};
const ECC_L=1,GF_EXP=new Array(512),GF_LOG=new Array(256);(function(){let x=1;for(let i=0;i<255;i++){GF_EXP[i]=x;GF_LOG[x]=i;x<<=1;if(x&0x100)x^=0x11d}for(let i=255;i<512;i++)GF_EXP[i]=GF_EXP[i-255]})();function gfMul(x,y){if(x===0||y===0)return 0;return GF_EXP[GF_LOG[x]+GF_LOG[y]]}
function polyMul(p,q){const r=new Array(p.length+q.length-1).fill(0);for(let i=0;i<p.length;i++)for(let j=0;j<q.length;j++)r[i+j]^=gfMul(p[i],q[j]);return r}
function polyMod(msg,gen){const res=msg.slice();for(let i=0;i<=msg.length-gen.length;i++){const coef=res[i];if(coef!==0){for(let j=1;j<gen.length;j++)res[i+j]^=gfMul(gen[j],coef)}}return res.slice(res.length-gen.length+1)}
function rsGenerator(deg){let g=[1];for(let i=0;i<deg;i++)g=polyMul(g,[1,GF_EXP[i]]);return g}
const RS_BLOCKS={1:{v:1,size:19,ec:7},2:{v:2,size:34,ec:10},3:{v:3,size:55,ec:15},4:{v:4,size:80,ec:20},5:{v:5,size:108,ec:26},6:{v:6,size:136,ec:18},7:{v:7,size:156,ec:20},8:{v:8,size:194,ec:24},9:{v:9,size:232,ec:30}};function capacityVer9(){return RS_BLOCKS[9].size}
function createDataBytes(dataBytes,ecCount){const gen=rsGenerator(ecCount),msg=dataBytes.concat(new Array(ecCount).fill(0)),ec=polyMod(msg,gen);return {data:dataBytes,ec}}
function makeMatrix(ver,data){const n=17+4*ver,m=P(n);function placeFinder(x,y){for(let dy=-1;dy<=7;dy++)for(let dx=-1;dx<=7;dx++){const xx=x+dx,yy=y+dy;if(xx<0||xx>=n||yy<0||yy>=n)continue;let v=false;if(dx>=0&&dx<=6&&dy>=0&&dy<=6){const a=Math.max(Math.abs(dx-3),Math.abs(dy-3));v=a===3||dx===0||dx===6||dy===0||dy===6}m[yy][xx]=v}}
placeFinder(0,0);placeFinder(n-7,0);placeFinder(0,n-7);for(let i=8;i<n-8;i++){const v=i%2===0;m[6][i]=v;m[i][6]=v}
const fmt=[1,0,1,0,1,0,0,1,1,0,0,0,1,0,0];function placeFormat(mask){const bits=fmt.slice();let i=0;for(let y=0;y<6;y++)m[y][8]=bits[i++]===1; m[7][8]=bits[i++]===1; m[8][8]=bits[i++]===1; m[8][7]=bits[i++]===1; for(let x=5;x>=0;x--)m[8][x]=bits[i++]===1;
for(let y=n-1;y>=n-7;y--)m[y][8]=bits[i++]===1; for(let x=n-1;x>=n-8;x--)m[8][x]=bits[i++]===1}
function nextPos(x,y,up){while(true){if(x===6)x--;if(!m[y][x]&&m[y][x]!==false){}if(typeof m[y][x]==='boolean'){};return}
}
let dirUp=true,x=n-1,y=n-1;let idx=0;function isReserved(xx,yy){if(xx===6||yy===6)return true;if(xx<9&&yy<9)return true;if(xx>n-9&&yy<9)return true;if(xx<9&&yy>n-9)return true;return false}
while(y>=0&&x>=0){for(let i=0;i<2;i++){const xx=x-(i===0?0:1),yy=y;if(!isReserved(xx,yy)&&m[yy][xx]===false){const bit=((data[idx>>3]>>(7-(idx&7)))&1)===1;m[yy][xx]=bit;idx++}}if(dirUp){y--;if(y<0){y=0;x-=2;dirUp=false}}else{y++;if(y>=n){y=n-1;x-=2;dirUp=true}}if(x===6)x--}
placeFormat(0);return m}
export function generateQrSvg(text,size=140){const ver=9,cap=capacityVer9();const mode=4;const bb=new B();bb.put(mode,4);const bytes=new TextEncoder().encode(String(text||''));bb.put(bytes.length,8);for(let i=0;i<bytes.length;i++)bb.put(bytes[i],8);bb.put(0,4);while(bb.length%8!==0)bb.putBit(false);const maxData=RS_BLOCKS[ver].size-RS_BLOCKS[ver].ec;let dataArr=Array.from(bb.buffer).slice(0,maxData);if(dataArr.length<maxData){dataArr=dataArr.concat(new Array(maxData-dataArr.length).fill(0))}const blocks=createDataBytes(dataArr,RS_BLOCKS[ver].ec);const joined=blocks.data.concat(blocks.ec);const m=makeMatrix(ver,joined);const n=m.length,scale=Math.max(1,Math.floor(size/n));const s=scale*n;let path='';for(let y=0;y<n;y++){for(let x=0;x<n;x++){if(m[y][x]){path+=`M${x*scale},${y*scale}h${scale}v${scale}h-${scale}z`}}}
return `<svg xmlns="http://www.w3.org/2000/svg" width="${s}" height="${s}" viewBox="0 0 ${s} ${s}" shape-rendering="crispEdges" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><rect width="${s}" height="${s}" fill="#fff"/><path d="${path}" fill="#000"/></svg>`}
